_wandb:
    value:
        cli_version: 0.25.1
        e:
            hkdl32mde7nacp0bgdk7p8rsrx5714pc:
                codePath: my_gan.ipynb
                colab: https://colab.research.google.com/notebook#fileId=1wnjpelULXRD6GKyFX1sOi7txYt2pAso-
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "120942624768"
                        used: "53094621184"
                email: elleth956428@gmail.com
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-15ff9373-1d65-3ab6-d3dd-e5f7cfa50d85
                host: 5cc090c05334
                memory:
                    total: "13605834752"
                os: Linux-6.6.113+-x86_64-with-glibc2.35
                program: my_gan.ipynb
                python: CPython 3.12.12
                root: /content/drive/MyDrive/GAN_project
                startedAt: "2026-03-21T10:44:23.199118Z"
                writerId: hkdl32mde7nacp0bgdk7p8rsrx5714pc
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 105
            "2":
                - 1
                - 5
                - 41
                - 53
                - 105
            "3":
                - 2
                - 13
            "4": 3.12.12
            "5": 0.25.1
            "8":
                - 1
                - 12
            "12": 0.25.1
            "13": linux-x86_64
