_wandb:
    value:
        cli_version: 0.26.1
        e:
            1bkkjtf1op8s3232yb1vc2s91i3mg98x:
                codePath: my_gan.ipynb
                colab: https://colab.research.google.com/notebook#fileId=1wnjpelULXRD6GKyFX1sOi7txYt2pAso-
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "120942624768"
                        used: "52483530752"
                email: elleth956428@gmail.com
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-a56ace87-da94-6902-9d18-3baf57c5c349
                host: aa62bb9d387f
                memory:
                    total: "13605834752"
                os: Linux-6.6.113+-x86_64-with-glibc2.35
                program: my_gan.ipynb
                python: CPython 3.12.13
                root: /content/drive/MyDrive/GAN_project
                startedAt: "2026-05-02T12:25:13.799985Z"
                writerId: 1bkkjtf1op8s3232yb1vc2s91i3mg98x
        m:
            - "1": epoch
              "6":
                - 3
              "7": []
            - "1": train/critic/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/critic/adv_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/generator/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": metric_0
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/generator/adv_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/generator/energy_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/generator/weighted_energy_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/regularizer/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/discriminator/grad_norm
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/generator/grad_norm
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": metric_1
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 7
                - 13
            "4": 3.12.13
            "5": 0.26.1
            "8":
                - 1
                - 12
            "12": 0.26.1
            "13": linux-x86_64
